// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers"

const context = require.context(".", true, /\.js$/)
application.load(definitionsFromContext(context))

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MountainSidebarController from "./mountain_sidebar_controller"
application.register("mountain-sidebar", MountainSidebarController)
