module.exports = {
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
  ],
  safelist: [
    'bg-gray-200',
    'bg-sky-300',
    'bg-orange-300',
    'bg-blue-600',
    'h-full',
    'overflow-hidden',
    'overflow-y-auto',
    'min-h-screen',
    'h-screen',
    'rounded-full',
    'flex',
    'flex-1',
    'overflow-hidden',
    'h-full',
    'fixed',
    'right-0',
    'w-56',
    'bg-white',
    'border-l',
    'border-black',
    'shadow-lg',
    'z-50',
    'hidden',
    'overflow-y-auto',
    'mr-56',
    'px-5',
    'w-80',
    'text-yellow-500',
    'text-xl',
    'text-gray-400',
    'bi-star',
    'bi-star-fill',
    'bi',
    'text-5xl',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded',
    'px-5',
    'py-1',
    'gsi-material-button',
    'gsi-material-button-state',
    'gsi-material-button-content-wrapper',
    'gsi-material-button-icon',
    'gsi-material-button-contents',
    'text-white',
    'font-medium',
    'border-gray-300',
    'hover:bg-gray-50',
    'focus:outline-none',
    'focus:ring-2',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
