// tailwind.config.js
module.exports = {
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
  ],
  safelist: [
    'bg-blue-600',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-orange-300',
    'bg-red-600',
    'bg-sky-300',
    'bg-white',

    'border-black',
    'border-gray-300',
    'border-l',
    'shadow-md',
    'shadow-lg',
    'shadow-[0_8px_24px_rgba(0,0,0,0.2),_0_0_10px_rgba(0,0,0,0.1)]',
    'hover:shadow-2xl',
    'hover:shadow-[0_12px_30px_rgba(0,0,0,0.25),_0_0_15px_rgba(0,0,0,0.15)]',

    'block',
    'flex',
    'flex-1',
    'inline-flex',
    'items-center',
    'justify-center',
    'container',
    'w-50',
    'w-56',
    'w-60',
    'w-80',
    'w-fit',
    'h-50',
    'h-full',
    'h-screen',
    'h-[calc(100vh-64px)]',
    'min-h-screen',
    'mx-auto',
    'ml-4',
    'mr-56',

    'p-2',
    'p-4',
    'p-6',
    'px-5',
    'py-1',
    'mb-2',
    'mb-4',
    'mb-6',
    'mt-?',

    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-xl',
    'text-lg',
    'text-base',
    'text-white',
    'text-gray-400',
    'text-gray-600',
    'text-gray-700',
    'text-blue-600',
    'text-green-600',
    'text-yellow-500',
    'font-medium',
    'font-semibold',
    'font-bold',

    'rounded',
    'rounded-md',
    'rounded-full',
    'rounded-lg',
    'rounded-2xl',
    'border',
    'overflow-hidden',
    'overflow-y-auto',
    'transform',
    'transition',
    'transition-all',
    'transition-transform',
    'duration-300',
    'duration-1500',
    'ease-in-out',
    'ease-out',
    'opacity-0',
    'opacity-100',
    '-translate-x-10',
    '-translate-x-full',
    'translate-x-0',
    'hover:-translate-y-2',
    'hover:underline',

    'hover:bg-blue-500',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-300',
    'hover:bg-red-100',
    'hover:bg-red-500',
    'focus:outline-none',
    'focus:ring-2',
    'cursor-pointer',

    'sm:flex-row',
    'lg:hidden',
    'lg:flex',
    'lg:relative',
    'lg:w-60',
    'lg:h-auto',
    'lg:h-full',
    'lg:top-0',
    'lg:left-0',
    'lg:transform-none',
    'lg:translate-x-0',

    'fixed',
    'top-0',
    'top-16',
    'right-0',
    'left-0',
    'bottom-0',
    'bottom-12',
    'z-40',
    'z-50',

    'swiper',
    'swiper-button-next',
    'swiper-button-prev',
    'swiper-slide',
    'swiper-wrapper',
    'bi',
    'bi-star',
    'bi-star-fill',
    'gsi-material-button',
    'gsi-material-button-state',
    'gsi-material-button-content-wrapper',
    'gsi-material-button-icon',
    'gsi-material-button-contents',
    'opacity-0',
    'opacity-100',
    'translate-y-0',
    'translate-y-5',
    'transition-all',
    'duration-700',
    'ease-out',
    'rounded-2xl',
    'shadow-lg',
    'lg:rounded-none',
    'lg:shadow-none',
    'lg:border-none',
    'lg:overflow-visible',
    'rounded-lg',
    'shadow-md',
    'transition-all',
    'duration-300',
    'ease-out',
    'hover:-translate-y-1',
    'hover:scale-105',
    'hover:shadow-xl',
  ],
  theme: {
    extend: {
      keyframes: {
        "slide-up": {
          "0%": { opacity: 0, transform: "translateY(30px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.6s ease-out",
      },
    },
  },
  plugins: [],
};
